GET http://localhost:3000/api/games/1 HTTP/1.1
content-type: application/json
authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJhdWQiOiJjbGllbnRfY3JlZGVudGlhbHMiLCJleHAiOjE3ODg2MDU1NDgsInN1YiI6IjkyNTI1ODQwIn0._2sRVFLCXlBNXGmtbw9f5wJ7EMMCB6HRBXcHiVU8noA